### ISSUE TITLE
OverlayLayout needed

### ISSUE THREAD

**Issue by ki0k1** [linkedin/LayoutKit#100]
Hello guys, i don't understand how make layout in my project like on picture:
<img width="633" alt="screen shot 2017-02-09 at 2 09 02 pm" src="https://cloud.githubusercontent.com/assets/5331145/22780886/5875e29c-eed1-11e6-9697-63489fe865dc.png">

2 and 3 index is LabelLayout

Please help :/

**Comment by stevejcox** [comment]
hey @ki0k1 

I've had some similar challenges and couldn't work out the best LayoutKit way to do it. Hopefully someone else can offer a better solution.

However the way I achieved this was to simply create a subview where necessary. 

In your example I would have 1 and 2 in the same view (add 2 as a sub layout to 1), then add a basic UIView and add 3 to that.

**Comment by staguer** [comment]
There's definitely a need for an overlay layout.

You can build one yourself, Issue #90 actually has a sample project that happens to include an OverlayLayout.swift, which might help as a starting example. 

A poor workaround might be to add a zero-size layout in that corner and add to it a sublayout that extends outside of its bounds. Whether this would work probably depends on whether Layout 3 has a fixed static size.

**Comment by dgattey** [comment]
I can take this on!

**Comment by dgattey** [comment]
Here’s the PR for OverlayLayout https://github.com/linkedin/LayoutKit/pull/127

**Comment by staguer** [comment]
I wonder why I can't assign this issue to @dgattey

**Comment by nicksnyder** [comment]
@staguer https://github.com/isaacs/github/issues/100

**Comment by dgattey** [comment]
Available in latest!

**Comment by staguer** [comment]
Thanks!
