### ISSUE TITLE
Benchmark crash

### ISSUE THREAD

**Issue by iwheelbuy** [linkedin/LayoutKit#103]
Hello. I just wanted to post here a benchmark crash. Feel free to close the issue!
Xcode 8.2.1, iPhone SE 10.2 simulator 14C89, UICollectionView Manual Layout feed.
<img width="1392" alt="2017-03-12 10 47 34" src="https://cloud.githubusercontent.com/assets/2524584/23828859/0382e128-0712-11e7-8303-de23e8f5b490.png">

**Comment by jingwei-huang1** [comment]
PR to fix this issue: https://github.com/linkedin/LayoutKit/pull/110/

**Comment by jingwei-huang1** [comment]
PR https://github.com/linkedin/LayoutKit/pull/121 merged
