### ISSUE TITLE
Making backgroundLayoutQueue open or public

### ISSUE THREAD

**Issue by thekirankumar** [linkedin/LayoutKit#104]
We are using LayoutKit's `ReloadableViewLayoutAdapter` along with Realm. But Realm objects can only be accessed from the thread it was created in. Due to this limitation, we are not able to create a Layout since this Layout depends on Realm objects since it throws an exception 
`'RLMException', reason: 'Realm accessed from incorrect thread'`

Making the `backgroundLayoutQueue` property in `ReloadableViewLayoutAdapter` public or open  will help us get a reference of the underlying queue on which we can retrieve our realm objects.

**Comment by staguer** [comment]
Making it public sounds reasonable.
