### ISSUE TITLE
GestureRecognizer not receiving taps after batchUpdate

### ISSUE THREAD

**Issue by Rep2** [linkedin/LayoutKit#107]
I am deleting one item from collectionView and reloading collection using `LayoutAdapterCollectionView.reload`. If I pass batchUpdates object to the call rest of the presented items stop receiving taps. If I do not pass batchUpdates object everything works fine.

Any idea why this happens?

**Comment by staguer** [comment]
@Rep2 Hi, do you set the tap gesture recognizer in a layout's config block? If the views get re-created, the config blocks will get called again and the gesture recognizer should get attached to the new view.

**Comment by Rep2** [comment]
Thanks, that solved the problem.
