### ISSUE TITLE
ReloadableViewLayoutAdapter batchUpdates animation style

### ISSUE THREAD

**Issue by Rep2** [linkedin/LayoutKit#124]
Hi. I am finding ReloadableViewLayoutAdapter quite useful, but most of the methods are not open making it hard to use it for anything but the simplest of cases. Is there any reason for this?

For example, I need to change UITableView batchUpdates animation style. Method `public func perform(batchUpdates: BatchUpdates)` in `extension UITableView: ReloadableView` uses .automatic and cannot be overridden.

`open func reload<T: Collection, U: Collection>` in `ReloadableViewLayoutAdapter` is open but `var currentArrangement` is `internal(set)` because of which it is needed to call `super. reload`. As such it is not possible custom reload and call custom batchUpdates.

I ended up implementing custom ReloadableViewLayoutAdapter. Any better ideas? Would it be possible to make open some of the methods?

**Comment by nicksnyder** [comment]
All else equal, I tried to limit the public API for simplicity. It is hard to predict what others will find useful and it is much easier to make things open later than it is to refactor an API that has everything open by default.

If you think there are improvements that could be made to the API to make it easier to use/extend, please submit a PR with an explanation (separate independent changes into different PRs).
We have accepted PRs like this in the past: https://github.com/linkedin/LayoutKit/pull/105

Some things may be intentionally not open, but that is best discussed on an actual PR.

**Comment by staguer** [comment]
One thing that we did not do in #105 but probably should have is to add a code comment giving an example scenario when overriding that method would be useful.

**Comment by Rep2** [comment]
Great. Will do tomorrow.

**Comment by Rep2** [comment]
Making `func perform(batchUpdates: BatchUpdates)` in `extension UITableView: ReloadableView` open and overriding it results in `Declarations from extensions cannot be overridden yet` because `BatchUpdates` is struct and as such cannot be exposed in objc.

Would you consider making `BatchUpdates` a class?

Other solution would be to add struct specifying animation style to either `func perform(batchUpdates: BatchUpdates)` or `BatchUpdates`.

**Comment by staguer** [comment]
I don't mind making it a class. @nicksnyder ?

**Comment by nicksnyder** [comment]
> Declarations from extensions cannot be overridden yet because BatchUpdates is struct

Are you sure? The error message seems to indicate that this is a problem because `perform` is a method declared in an extension.

It seems like the solution would be to add the data to BatchUpdates. This animation data seems like it would only be relevant to UITableView though.

**Comment by Rep2** [comment]
I have misspoken slightly. It's not about making `BatchUpdates` a class, but about making it exposable to objc. To do this it needs to be a class and inherit from NSObject.

Methods that are declared in extensions and can be exposed to objc, can be overriden. For example both `open func reloadDataSynchronously()` and `open func registerViews(withReuseIdentifier reuseIdentifier: String)` declared in the same extension can be overriden. 

Im also fine with adding the data to `BatchUpdates`.

**Comment by nicksnyder** [comment]
I think I am fine with turning BatchUpdates into a class
