### ISSUE TITLE
LayoutKit CI build is broken

### ISSUE THREAD

**Issue by nicksnyder** [linkedin/LayoutKit#134]
As of https://github.com/linkedin/LayoutKit/pull/132/files#diff-0b83f9dedf40d7356e5ca147a077acb4 the build script that runs on Travis no longer builds or runs tests for the main LayoutKit target.

Before (tests run): https://travis-ci.org/linkedin/LayoutKit/builds/223716700
After (no tests run): https://travis-ci.org/linkedin/LayoutKit/builds/225308216
Current (no tests run): https://travis-ci.org/linkedin/LayoutKit/builds/225442466

The build script used to be a chain of commands linked with `&&` so that any failure would cause the whole script to fail. As it is now, the first command fails, but the next two commands still run and the build script (erroneously) passes.

Please do not merge or commit any more changes to master until this is fixed.

**Comment by jingwei-huang1** [comment]
@nicksnyder The build failed was because iOS simulator 9.3 is no longer available. 

List all available simulators: https://travis-ci.org/linkedin/LayoutKit/builds/225469316
After removing iOS simulator 9.3 from destination: https://travis-ci.org/linkedin/LayoutKit/builds/225640597

I am going to raise the PR for this. In the meanwhile, I am going to investigate why 9.3 is no longer available.

**Comment by nicksnyder** [comment]
The bigger problem is that a build step failed (the most important one) but Travis CI didn't fail.

**Comment by jingwei-huang1** [comment]
Link to PR: https://github.com/linkedin/LayoutKit/pull/135

**Comment by jingwei-huang1** [comment]
@nicksnyder 
In the scripts, I added two simulators below,
```
xcrun simctl create 'iPhone 6' \
    com.apple.CoreSimulator.SimDeviceType.iPhone-5 \
    com.apple.CoreSimulator.SimRuntime.iOS-9-3 &&
xcrun simctl create 'iPhone 6 Plus' \
    com.apple.CoreSimulator.SimDeviceType.iPhone-5 \
    com.apple.CoreSimulator.SimRuntime.iOS-9-3 &&
```
It passes the 9.3 tests
https://api.travis-ci.org/jobs/225843372/log.txt?deansi=true

Do you think if that is a good approach?

**Comment by nicksnyder** [comment]
Seems fine to me

**Comment by jingwei-huang1** [comment]
Travis CI fixed the issue. PR to add this back https://github.com/linkedin/LayoutKit/pull/139

**Comment by jingwei-huang1** [comment]
#139 merged
