### ISSUE TITLE
High memory usage if load a large amout of items at once

### ISSUE THREAD

**Issue by bcse** [linkedin/LayoutKit#142]
I noticed the memory usage is very high if I changed items number.
I tested by changing this line: https://github.com/linkedin/LayoutKit/blob/2c89e0b63552/LayoutKitSampleApp/FeedBaseViewController.swift#L41
And here is my test results:

- 1000: 12 MB
- 2000: 130 MB*
- 3000: 300 MB*
- 4000: 500 MB*
- 5000: 800 MB* -- On some devices, this caused out-of-memory

`*` This is top memory usage, it decreased after it hit the top

I also did another test. I call reload with 1000 items at the first time. And then wait a second, call reload with 2000 items. And then wait a second, call reload with 3000 items. And keeps doing this until 10000 items. In this case, memory is around 40 MB.

**Comment by nicksnyder** [comment]
I don't understand the first test scenario. FeedBaseViewController is a base class, what child class were you performing the test on?

> I also did another test.  In this case, memory is around 40 MB.

You are saying the peak memory usage in the second scenario is 40 MB?

ReloadableViewLayoutAdapter stores all layouts in memory and does a few transformations on reload (so it may have peak memory usage multiples more than necessary). We don't have lists of items that long in the LinkedIn app, so it isn't much of a concern for us.

If this is a real-world concern for you, PRs to improve memory usage are welcome :)

**Comment by bcse** [comment]
For the first scenario, I am tested with FeedTableViewController.

Currently I am load all data from a local DB and feed in to ReloadableViewLayoutAdapter at once. Now I think I should try to load them incrementally. Thanks for your help. 👍
