### ISSUE TITLE
Compare LayoutKit with other layouting methods

### ISSUE THREAD

**Issue by lucmirego** [linkedin/LayoutKit#144]
Hi,

http://layoutkit.org/benchmarks is really really nice, and display clearly that LayoutKit is fast. I was just wondering what was the complexity of the UICollectionView's cell in the benchmark? How many views? Can you share a screenshot of the cell's content?

We would like to create a standard benchmark to compare all iOS layout frameworks, and your test is clearly really interesting. 

Thanks to participates in the iOS open source community!

Regards

**Comment by lucmirego** [comment]
OK, I just found your benchmark in your app. Sorry

**Comment by jingwei-huang1** [comment]
No worries. 

We are using https://github.com/diwu/DWURecyclingAlert to benchmark the performance. Also, we have a stopwatch (`Stopwatch.swift`) that can record elapsed time and benchmark closures.
