### ISSUE TITLE
How can we use LayoutKit with UIAppearance

### ISSUE THREAD

**Issue by Sashke** [linkedin/LayoutKit#146]
We have some target's that using same UI but with different color schemes. We setting color schemes via UIAppearance.
For example, without LayoutKit, we have cell (exampleCell) with 3 labels (labelOne, labelTwo, labelThree) which have 3 properties: labelOneTextColor, LabelTwoTextColor and labelThreeTextColor. We can update this properties via UIAppearance like ExampleCell.appearance.setLabelOneTextColor(newColor).

In LayoutKit we don't have access to specific views. Are there any ways to use UIAppearance with LayoutKit?

Sorry for my english

**Comment by nicksnyder** [comment]
You may capture the views created by LayoutKit in the `config` block that you pass in to the constructor. Does that solve your problem?
