### ISSUE TITLE
TextViewLayout - Why is isSelectable forced to false?

### ISSUE THREAD

**Issue by spekke** [linkedin/LayoutKit#152]
What's the reason isSelectable is forced to false in TextViewLayout?

```swift
open override func configure(view textView: TextView) {
    super.configure(view: textView)
    ....
    textView.isSelectable = false
```

This prevents interactions with links etc. 

From docs:
> This property controls the ability of the user to select content and interact with URLs and text attachments. The default value is true.

**Comment by chriscuecal** [comment]
I would like to know the reason for this as well.

**Comment by jingwei-huang1** [comment]
Originally, when I built it, it has the issue that the view of "copy, share..." didn't display correctly for some reason.

I just re-tested on iOS 10&11 and it looks good. I will move it before the config to allow the overridden of `isSelectable`

**Comment by chriscuecal** [comment]
Great! Thank you!

**Comment by jingwei-huang1** [comment]
Raised PR https://github.com/linkedin/LayoutKit/pull/153

**Comment by spekke** [comment]
Ah, cool. Thanks!
