### ISSUE TITLE
StackLayout fillEqualSpacing leaving a gap at the bottom

### ISSUE THREAD

**Issue by domasn** [linkedin/LayoutKit#159]
`StackLayout` doesn't fill all of the spacing using `.fillEqualSpacing` distribution if non-zero `spacing` parameter is passed.

The problem is in [`StackLayout.distributionConfig`](https://github.com/linkedin/LayoutKit/blob/2df3a704342b3f7e6a6607e52006834f675c2bc5/Sources/Layouts/StackLayout.swift#L221) where it calculates the `axisSpacing` not taking into account the spaces that were already added during the `measurement` phase. Actual `excessAxisLength` for `.fillEqualSpacing` should be increased by `numberOfSpaces * spacing` so it can be redistrubuted.

See this example [playground gist](https://gist.github.com/domasn/b8cb775386fb3208512376e9dfbfa2fc) to reproduce the following screenshot: 
<img width="591" alt="actual" src="https://user-images.githubusercontent.com/7569279/30324215-eadcc916-97c8-11e7-86d2-b73419d412fd.png">

The expected behavior IMHO looks like this:
<img width="591" alt="expected" src="https://user-images.githubusercontent.com/7569279/30324301-3646609c-97c9-11e7-944b-cf8b0052cd60.png">

**Comment by nicksnyder** [comment]
Thanks for the detailed bug report and PR to fix. The expected behavior that you described is what is supposed to happen.
