### ISSUE TITLE
Features proposal

### ISSUE THREAD

**Issue by lucabartoletti** [linkedin/LayoutKit#17]
I started using this framework in a sample project. Great work and thanks for sharing.
I spent some time myself working on something similar, as a side project, and i'm considering to switch to LayoutKit cause it is far head on what I have.

Things that I'd like to add:
- **Label baseline alignment**: Be able to align labels by baseline in an horizontal layout
- **Center on a specific element of the stack**:  Let's say a stack contains two layouts [A][B], if I set .center as aligment for the stack, than the stack's container will set the stack position based on the mid point of it's size. There are cases where I want to center the stack on a specifc element. 

For example in this Stack I have to elements the dot and the text. That text should be centered.
![Sample](http://i.imgur.com/OVvFOff.png)
A solution to this specific example could be to create an empty SizeLayout as third element of the stack with the same width than the first one. But this could be more complicated with dynamic elements and it should be possible without have to create more layout elements than necessary.

- **Action support**: Now I can add a button as part of the layout and than regenerate the Layout in response to an user action. Could be useful to have a native support for states (Normal, Highlighted) in a way that the view could automatically update to reflect a given state. i.e. having a state parameter in the view config block
- **Traslation**: Ability to apply a traslation to a view position after the layout phase by absolute value or by percentage on the container size.
- **Max/Min size constraints**: Ability to apply a max/min size to a Layout, so that it can still adapt it's size to the size of it's content and at the same time allows to specify min/max constraints.

Please let me know if those features are on you list and if you think if they make sense or not.
From your architecture I see that I can develop those things has private  layouts but I'd like to know your feedbacks, if you have similar things on your todo list and eventually share my changes if they can be useful.

**Comment by nicksnyder** [comment]
Thanks for sharing your ideas Luca!

It would be helpful if you could create a single issue for each idea so we can discuss and track them independently.

**Comment by nicksnyder** [comment]
I created #18 to discuss min/max size constraints

**Comment by lucabartoletti** [comment]
Thanks!
 I created #19, #20, #21 and #22 to cover those proposal. Closing this
