### ISSUE TITLE
min/max size constraints for layouts

### ISSUE THREAD

**Issue by nicksnyder** [linkedin/LayoutKit#18]
Currently `SizeLayout` allows layouts to have a specific length along one or both dimensions.

It would be useful to be able to specify maximum width/height and minimum width/height for a nested layout.

One option would be to create a `MinSizeLayout` and a `MaxSizeLayout`. Unsure if it would make sense to combine these into one layout (e.,g. `SizeRangeLayout`), or even combine them with `SizeLayout`.

If we stick with separate layouts, then we might also want to rename `SizeLayout` to `ExactSizeLayout`

**Comment by lucabartoletti** [comment]
Thanks for opening this, probably I prefer the solution of SizeRangeLayout with convience init methods to just specify just MaxSize or MaxWidth or MaxHeight or MinSize or MinWidth or MinHeight.

I need this for my layouts so happy to work on it.

**Comment by nicksnyder** [comment]
I think it might make sense to put this functionality in `SizeLayout`. Exact size is just a special case of a size range where max size == min size.

Something like this (I omitted all the other layout parameters for clarity)

```swift
public class SizeLayout {

    public let minWidth: CGFloat?
    public let maxWidth: CGFloat?
    public let minHeight: CGFloat?
    public let maxHeight: CGFloat?

    public init(minWidth: CGFloat? = nil,
                maxWidth: CGFloat? = nil,
                minHeight: CGFloat? = nil,
                maxHeight: CGFloat? = nil) {

        self.minWidth = minWidth
        self.maxWidth = maxWidth
        self.minHeight = minHeight
        self.maxHeight = maxHeight
    }

    public convenience init(width: CGFloat? = nil, height: CGFloat? = nil) {
        self.init(minWidth: width, maxWidth: width, minHeight: height, maxHeight: height)
    }

    public convenience init(width: CGFloat, minHeight: CGFloat? = nil, maxHeight: CGFloat? = nil) {
        self.init(minWidth: width, maxWidth: width, minHeight: minHeight, maxHeight: maxHeight)
    }

    public convenience init(height: CGFloat, minWidth: CGFloat? = nil, maxWidth: CGFloat? = nil) {
        self.init(minWidth: minWidth, maxWidth: maxWidth, minHeight: height, maxHeight: height)
    }

    public convenience init(size: CGSize) {
        self.init(width: size.width, height: size.height)
    }

    public convenience init(maxSize: CGSize) {
        self.init(maxWidth: maxSize.width, maxHeight: maxSize.height)
    }

    public convenience init(minSize: CGSize) {
        self.init(minWidth: minSize.width, minHeight: minSize.height)
    }
}

SizeLayout(height: 100)
SizeLayout(height: 100, width: 75)
SizeLayout(height: 100, minWidth: 50)
SizeLayout(height: 100, maxWidth: 100)
SizeLayout(height: 100, minWidth: 50, maxWidth: 100)
```

**Comment by nicksnyder** [comment]
@lucabartoletti Have you had a chance to work on this? Have any thoughts on my proposal?
