### ISSUE TITLE
Using LayoutKit with `UITableViewDataSource`

### ISSUE THREAD

**Issue by codeOfRobin** [linkedin/LayoutKit#195]
Hey! I'm trying to use LayoutKit with a regular `UITableViewDataSource`/`UICollectionViewDataSource`. Looking through `StackView`s code, it isn't quite clear how this would work 😕 .

1. How would you convert a `Layout` to a UITableViewCell? How do you induce Layout?
2. How would you calculate the height for each row/size at each indexPath?

**Comment by staguer** [comment]
@codeOfRobin for a `UITableView` or `UICollectionView` I'd recommend using `ReloadableViewLayoutAdapter`. It produces layout arrangements from the layouts supplied by your code and uses that to populate the cells and respond to the sizing callbacks.
