### ISSUE TITLE
LabelLayout goes beyond screen width

### ISSUE THREAD

**Issue by kartikthapar** [linkedin/LayoutKit#204]
Here's a wrapper for a bunch of components/layouts but currently only hosting a label layout.

```
public class DisplayComponent: InsetLayout<UIView> {
  init() {
    super.init(
      insets: UIEdgeInsets(top: 32, left: 32, bottom: 32, right: 32),
      sublayout:
      StackLayout(
        axis: .vertical,
        spacing: 32,
        alignment: .center,
        viewReuseId: "login-stack",
        sublayouts: [
          LabelLayout(
            text: "This is greater than a single line text",
            font: UIFont.font(ofSize: .extraLarge, withWeight: .heavy),
            numberOfLines: 2,
            alignment: Alignment.topFill,
            flexibility: .max,
            viewReuseId: "hello-login"
           ),
        ],
        config: { (view) in
          view.backgroundColor = UIColor.green
      })
    )
  }
}
```

Its called here:

```
class DisplayViewController: UIViewController {
  override func viewDidLoad() {
    view.backgroundColor = .white

    DisplayComponent().arrangement().makeViews(in: view, direction: UserInterfaceLayoutDirection.leftToRight)
  }
}
```

Here's the result:

<img width="423" alt="screen shot 2018-04-29 at 2 29 31 pm" src="https://user-images.githubusercontent.com/810861/39411181-cd120658-4bb9-11e8-992d-bfa4a9d2bb2a.png">

Now I am unsure what's wrong here:
- number of lines?
- alignment?

**Comment by kartikthapar** [comment]
<img width="414" alt="screen shot 2018-04-29 at 2 34 14 pm" src="https://user-images.githubusercontent.com/810861/39411214-85495b04-4bba-11e8-86f4-439e7b0e623f.png">

One more thing, if I just have a single label aligned using `Alignment.center`, it show up as above. It feels like the width of this containing view is wrong but there is nothing much that is going on.

**Comment by tysonkerridge** [comment]
Just from looking at the code, without testing it myself, it looks like the thing missing in your original post is giving a width/height when making your arrangement. 
```swift
Layout().arrangement().makeViews(in: view)
```
should be
```swift
Layout().arrangement(width: view.width, height: view.height).makeViews(in: view)
```
Without passing the sizing information, LayoutKit is going to calculate the frame at the largest size.
Check out `Layout.swift`, method starting at line 121 `arrangement(origin:width:height:)`

**Comment by richardtop** [comment]
@kartikthapar just out of interest, what font are you using in these examples?

**Comment by staguer** [comment]
The answer by @tysonkerridge appears to be correct. Closing the issue.
