### ISSUE TITLE
How to handle orientation change?

### ISSUE THREAD

**Issue by rikoschmidt** [linkedin/LayoutKit#25]
Hi, 

first of all thanks for open sourcing LayoutKit!

While experimenting with the Framework a bit I was wondering what'd be the best approach to handle orientation changes. 

Suppose we have the following layout and we want to adapt it to landscape mode on tilting the device. 

![screen shot 2016-07-19 at 08 14 22](https://cloud.githubusercontent.com/assets/3240957/16940374/c577f6c6-4d89-11e6-8eee-32607fb0faae.png)

Right now I handle this by creating the layout again from scratch if an orientation change occurs. 

````
    override func viewDidLoad() {
        super.viewDidLoad()
        
        title = "Layout Kit"
        
        let leftLayout = LabelLayout(text: "Left", alignment: LayoutKit.Alignment.topLeading) {label in
            label.backgroundColor = UIColor.purpleColor()
        }
        
        let rightLayout = LabelLayout(text: "Right", alignment: LayoutKit.Alignment.topTrailing ) { label in
            label.backgroundColor = UIColor.cyanColor()
        }
        
        let stackLayout = StackLayout(axis: .horizontal, spacing: 8, sublayouts: [leftLayout, rightLayout]) { (view) in
            view.backgroundColor = UIColor.blueColor()
        }
        
        insetLayout = InsetLayout(inset: 8, sublayout: stackLayout, config: nil)
        
        guard let insetLayout = insetLayout else { return }
        insetLayout.arrangement(width: view.bounds.size.width).makeViews(inView: containerView)
    }
    
    override func viewWillTransitionToSize(size: CGSize, withTransitionCoordinator coordinator: UIViewControllerTransitionCoordinator) {
        super.viewWillTransitionToSize(size, withTransitionCoordinator: coordinator)
        
        coordinator.animateAlongsideTransition({ (context) -> Void in
            guard let insetLayout = self.insetLayout else { return }
            insetLayout.arrangement(width: self.view.bounds.size.width).makeViews(inView: self.containerView)
        }) { (context) -> Void in }
    }
```

However I am wondering if there might be a better approach to this issue. 

Any help would be highly appreciated.

Cheers,
Riko

**Comment by nicksnyder** [comment]
Yes, the way to deal with orientation changes is to recompute the layout arrangement given the new width and/or height. It is perfectly fine to save the original layout object if the layout doesn't need to change (looks like you are already doing this, which is good!).

This might feel weird, but it is exactly what Auto Layout does, except Auto Layout is much slower :).

In LayoutKit 2.0 you will be able to provide view reuse identifiers so that the entire view hierarchy doesn't need to be recreated, and so that animations work as expected.

**Comment by rikoschmidt** [comment]
Thank you @nicksnyder!
