### ISSUE TITLE
SizeLayout<CustomView> will not actually create a CustomView

### ISSUE THREAD

**Issue by enums** [linkedin/LayoutKit#256]
`SizeLayout<CustomView>` will not actually create a `CustomView` instance. 
It doesn't feel right. 
Maybe `SizeLayout` should override `needsView` property return `true`? 
Or just make this property to be a storage property and set default value is `true`?

**Comment by zhongWJ** [comment]
You need pass `config` parameter when call `SizeLayout`'s init method.
`needsView` returns `true` when `config` property is not `nil`.
