### ISSUE TITLE
Do you still recommend LayoutKit

### ISSUE THREAD

**Issue by onmyway133** [linkedin/LayoutKit#263]
Hi, thanks for the great library. Correct me if I'm naive, but Auto Layout seems to get better performance https://developer.apple.com/videos/play/wwdc2018/220 sine iOS 12. Have you redone any benchmarks with Auto Layout to see the performance gain with LayoutKit, and would you still recommend LayoutKit, especially for big apps that uses UITableView/UICollectionView a lot ?

**Comment by AlexLittlejohn** [comment]
Rerunning this [LayoutFrameworkBenchmark](https://github.com/layoutBox/LayoutFrameworkBenchmark) on iOS 13 with the latest of each of these libraries still shows a significant performance gap between autolayout vs everything else.

**Comment by onmyway133** [comment]
@AlexLittlejohn thanks, does that mean Auto Layout is becoming slower now?

**Comment by AlexLittlejohn** [comment]
No, there is improvement but its still not as fast as the alternatives such as layoutkit

**Comment by onmyway133** [comment]
@AlexLittlejohn I use LayoutKit now not sure if it worths the effort to transition to Auto Layout. Thanks for answering
