### ISSUE TITLE
Convert to Swift 3

### ISSUE THREAD

**Issue by Andr3y-** [linkedin/LayoutKit#39]
Any idea when Swift3 support would be added, in particular for the latest Xcode 8 beta 6, which I am trying to build a project with (unsuccessfully)?

**Comment by nicksnyder** [comment]
The library itself should build with Swift 2.3 (which means it should work in Xcode 8).

I just discovered that some of other targets (e.g. sample app) didn't have the appropriate setting configured which would prevent it from building in Xcode 8. This will get fixed when I merge #40 (assuming tests pass).

Are you saying that a Swift 3 app can't depend on a Swift library written in Swift 2.3? What error do you get?

As far as migrating the library to Swift 3 goes, I probably won't do that until at least after Xcode 8 is released. It is a non-trivial change and we need it to work in Xcode 7 still.

There is a swift3 branch that you can check out but it is out of date (and based on LayoutKit 1.1.0 iirc).

**Comment by Andr3y-** [comment]
I tried building master branch with Xcode 7 and got this
`ld: /Users/username/repos/Network/Network/Frameworks/LayoutKit.framework/LayoutKit compiled with older version of Swift language (2.0) than previous files (3.0) for architecture x86_64
`

**Comment by nicksnyder** [comment]
@Andr3y- How are you integrating LayoutKit? Carthage? Cocoapods?

I haven't tried using LayoutKit from a Swift3 app yet so I am not exactly sure what is or is not expected to work.

**Comment by Andr3y-** [comment]
@nicksnyder I am using Carthage.
After doing some research, any non-Swift 3 code won't work in a Swift 3 project.

**Comment by nicksnyder** [comment]
@Andr3y- updated the `swift3` branch. Should build and pass tests on Xcode 8 beta 6.

**Comment by Andr3y-** [comment]
@nicksnyder amazing, thank you!
Tested: LayoutKit builds with Xcode 8 beta 6 through Cartage and project compiles with no issues

**Comment by nicksnyder** [comment]
Going to leave this issue open until the project is permanently converted to Swift 3.

**Comment by nicksnyder** [comment]
master is now converted to Swift 3.
