### ISSUE TITLE
CocoaPods Version Problem

### ISSUE THREAD

**Issue by desmond1008** [linkedin/LayoutKit#41]
I tried pod 'LayoutKit'
The version is 0.2.1 and the project created by Florian Krüger
I think it is not the correct kit.
Any idea what should I do to get the updated LayoutKit?

**Comment by nicksnyder** [comment]
It sounds like your pod repo is out of date. Try running `pod repo update`.

This is what you want:
https://cocoapods.org/pods/LayoutKit

**Comment by desmond1008** [comment]
Thank you for your help after update the repo.
