### ISSUE TITLE
not working for xcode 7.3.1 with swift 2.2

### ISSUE THREAD

**Issue by rahthakor** [linkedin/LayoutKit#52]
Hi,

I'm not able to install layoutkit using carthage.

Xcode Version : 7.3.1
Swift Version   : Apple Swift version 2.2 (swiftlang-703.0.18.5 clang-703.0.31)
                           Target: x86_64-apple-macosx10.9
cartfile             : github "linkedin/LayoutKit"

carthage update --platform iOS
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
A shell task (/usr/bin/xcrun xcodebuild -project "/Volumes/Workspace/Personal Projects/FrameworkPractices/Carthage/Checkouts/LayoutKit/LayoutKit.xcodeproj" -scheme LayoutKitExampleLayouts -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **

**Comment by nicksnyder** [comment]
Which version of LayoutKit are you trying to use?

LayoutKit 3.0.0 only supports Xcode 8 and Swift 3.

You should be able to use LayoutKit 2.0.1.

**Comment by rahthakor** [comment]
I was using latest version so might be it would be above 2.1.1.
I will give it try and update this issue.

**Comment by rahthakor** [comment]
@nicksnyder thank you. I used 2.1.1 for swift version 2.2.

**Comment by nicksnyder** [comment]
👍
