### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by AnanthaRajuC** [linkedin/LayoutKit#6]
https://github.com/linkedin/LayoutKit/LayoutKit/Layouts/LabelLayout.swift

https://github.com/linkedin/LayoutKit/LayoutKit/Layouts/SizeLayout.swift

https://github.com/linkedin/LayoutKit/LayoutKit/Layouts/InsetLayout.swift

https://github.com/linkedin/LayoutKit/LayoutKit/Layouts/StackLayout.swift

https://github.com/linkedin/LayoutKit/LayoutKitExampleLayouts/MiniProfileLayout.swift

https://github.com/linkedin/LayoutKit/LayoutKitExampleLayouts

and many more...

**Comment by nicksnyder** [comment]
Thanks for reporting this!
