### ISSUE TITLE
Why there isn't update in `BatchUpdates`

### ISSUE THREAD

**Issue by RoCry** [linkedin/LayoutKit#71]
How would I reload some rows of my table?

It seems very nature if there is updatedItems/Sections in  BatchUpdates.
What did I missed?

Thanks

**Comment by nicksnyder** [comment]
Should be pretty straightforward and easy to add support for this to [BatchUpdates](https://github.com/linkedin/LayoutKit/blob/master/LayoutKit/Views/BatchUpdates.swift) and [ReloadableView](https://github.com/linkedin/LayoutKit/blob/master/LayoutKit/Views/ReloadableView.swift).

Will also need to add or update unit tests.

@RoCry Would you like to work on this and submit a pull request?

**Comment by RoCry** [comment]
@nicksnyder Sure, will send the pull request soon.

**Comment by nicksnyder** [comment]
fixed by #72, thanks!
