### ISSUE TITLE
Should the config block execute at last?

### ISSUE THREAD

**Issue by RoCry** [linkedin/LayoutKit#75]
For instance: https://github.com/linkedin/LayoutKit/blob/master/LayoutKit/Layouts/LabelLayout.swift#L129-L137

Sometimes I want to change some property when configuration, it will be override by the initial setup.

Should the config block execute after initial setup will be better?

**Comment by nicksnyder** [comment]
Can you give an example? If you override any of the properties set in the function, then the computed layout will be incorrect.

**Comment by RoCry** [comment]
@nicksnyder That's very true, but what if you want to change the `text` after layout? 

For example, a time label that display the current time.

**Comment by AlexLittlejohn** [comment]
Use viewReuseId to make layout reuse cheaper. Then just update the layout every second.

**Comment by RoCry** [comment]
@AlexLittlejohn So your solution is re layout the whole layout stack, at the particular case, I know the layout that I want to change won't affect other layouts. Is there a better way?

**Comment by AlexLittlejohn** [comment]
That is the way, when updating a layout you use reuse ids to signal the whats changed, whats remaining the same and, by leaving them nil, the layouts that change every update.

**Comment by RoCry** [comment]
@AlexLittlejohn In my understanding, reuse id only help you to avoid init same view multi times, but the calculation of layout still there, right?

**Comment by nicksnyder** [comment]
@RoCry Sorry for slow response, I got sick this week.

> what if you want to change the text after layout?

Either re-layout, or capture a reference to the UILabel in the config block (be careful about retain cycles) and then update the text as you see fit. Obviously, if you do the latter then there is no guarantee that the text will not over/underflow the layout.

> reuse id only help you to avoid init same view multi times, but the calculation of layout still there, right?

Correct. Allocation and adding subviews is the slowest part. The layout itself is designed to be fast.

@AlexLittlejohn 's advice is correct. Using viewReuseId and recomputing the layout is almost certainly sufficient for your case if you are only doing layout once per second.

For now, the config block is first to prevent someone from accidentally overwriting a property that would potentially affect layout.
