### ISSUE TITLE
README: Broken link

### ISSUE THREAD

**Issue by markohlebar** [linkedin/LayoutKit#8]
The link to the blog post is broken. 
https://engineering.linkedin.com/blog/2016/06/open-sourcing-layoutkit--a-fast-view-layout-library-for-ios-appl

**Comment by nicksnyder** [comment]
Yeah, the blog post hasn't been published yet. Once it is, the link can be fixed.

**Comment by nicksnyder** [comment]
Blog post is now published so the link works.

**Comment by markohlebar** [comment]
Cheers!
