### ISSUE TITLE
How do you do the benchmark?

### ISSUE THREAD

**Issue by onmyway133** [linkedin/LayoutKit#80]
Hi, just curious on how the benchmark was performed http://layoutkit.org/benchmarks/ ? I assume that `layout time` is the time from before to after `reloadData`?

**Comment by nicksnyder** [comment]
How to run the benchmarks:
1. Checkout the code
2. Run the LayoutKitSampleApp target on a device
3. From the main menu, select BenchmarkViewController
4. Choose a benchmark to run
5. Results are logged to the console

> I assume that layout time is the time from before to after reloadData

Each benchmark iteration instantiates a new view controller with some data and then measures `view.layoutIfNeeded()` ([code](https://github.com/linkedin/LayoutKit/blob/master/LayoutKitSampleApp/Benchmarks/BenchmarkViewController.swift#L107)).
