### ISSUE TITLE
How to use tableView:didSelectRowAtIndexPath: delegate method with ReloadableViewLayoutAdapter?

### ISSUE THREAD

**Issue by AlanMcKen** [linkedin/LayoutKit#81]
How can I use tableView:didSelectRowAtIndexPath: or deselectRowAtIndexPath:animated: delegate methods for managing cell selection when I use ReloadableViewLayoutAdapter to create tableView (like in LayoutKitSampleApp)?

**Comment by nicksnyder** [comment]
ReloadableViewLayoutAdapter implements UITableViewDelegate methods so you have two options if you want to implement other UITableViewDelegate methods:

1. Subclass ReloadableViewLayoutAdapter, implement the additional methods (like `tableView:didSelectRowAtIndexPath:`), and then set your subclass as the delegate.
2. Create a new class that implements UITableViewDelegate and owns a ReloadableViewLayoutAdapter. This class will forward calls to the methods that ReloadableViewLayoutAdapter implements (and then you are free to implement additional UITableViewDelegate methods.

(1) is probably easier.

Hopefully this answers your question. If not, or if you run into difficulties implementing either of these options then please reopen this issue.
