### ISSUE TITLE
Best way of embedding a UIScrollView

### ISSUE THREAD

**Issue by stevejcox** [linkedin/LayoutKit#91]
Hi all,

I'm working on using UIScrollView's within layouts and am not sure if this is the best way:
https://gist.github.com/stevejcox/3007d694ef8394bdbfb97718349089de

Adding the content view as a sub layout of the SizeLayout<UIScrollView> causes the caption to size to the scrollview size rather than the content size. 

Any suggestions on how to improve this would be very helpful!

Thanks,
Steve

**Comment by stevejcox** [comment]
Ended up creating a new Layout class that extended SizeLayout but with a fixed height.

**Comment by YoonjaeYoo** [comment]
@stevejcox I've encounted the same issue. Can you share a little more on how you've done it?

**Comment by domasn** [comment]
Same problem.. See what works for my case in [this gist](https://gist.github.com/domasn/f8aaba53092f1c220f2054f8e946886b).
