### ISSUE TITLE
UITextView/UITextField in Layout

### ISSUE THREAD

**Issue by kioshimafx** [linkedin/LayoutKit#93]
Sorry for the stupid question, but the answer to it, i could not find. How i can add UITextView or UITextField in StackLayout/InsetLayout?

**Comment by stevejcox** [comment]
You could create it in a SizeLayout and make that the sub layout of an inset/stack

**Comment by kioshimafx** [comment]
But what if I need a dynamic calculation layout for UITextField? Not static size.

**Comment by stevejcox** [comment]
I'm no expert (new to LayoutKit).- so someone smarter may come back with a better answer. However SizeLayout will be compressed if the container size is smaller than it's size. 

So you could create a SizeLayout with the maximum size you would want and then rely on the InsetLayout to resize it. You'll need to play with the Flexibility / Alignment, but that's how I have gotten it to work with dynamic widths.

**Comment by kioshimafx** [comment]
@stevejcox  Not a bad solution. Thx steve :)
