### ISSUE TITLE
Clips to bounds is not respected

### ISSUE THREAD

**Issue by AttilaTheFun** [linkedin/LayoutKit#97]
I'm trying to add a drop shadow to a view spawned from an inset layout. In the config handler, I'm setting:
```
        view.layer.shadowColor = kShadowColor
        view.layer.shadowRadius = kShadowRadius
        view.layer.shadowOffset = kShadowOffset
        view.layer.masksToBounds = false
        view.clipsToBounds = false
```
But the shadow is not showing up. If I set the border color, however, that appears to work fine. What's going on here?

**Comment by AttilaTheFun** [comment]
After some investigation, it appears the issue has something to do with drawing outside the view's bounds. Regardless of how this layout system works, it shouldn't prevent views from drawing outside their bounds if they want to.

**Comment by nicksnyder** [comment]
I am not aware of any code in LayoutKit that would explicitly prevent you from doing this.

Can you provide a more complete example of what you are trying to do (ideally something reproducible in a playground)?

**Comment by AttilaTheFun** [comment]
@nicksnyder I was having a hard time getting LayoutKit to run inside a playground but here is a more complete example:
```
        let textLayout = LabelLayout(text: "This is a test")
        let subtitleLayout = LabelLayout(text: "Subtitle text")
        let stackLayout = StackLayout(axis: .vertical, spacing: 4, sublayouts: [textLayout, subtitleLayout])
        let insets = EdgeInsets(top: 12, left: 12, bottom: 12, right: 12)
        let cardLayout = InsetLayout(insets: insets, sublayout: stackLayout) { view in
            view.layer.shadowColor = UIColor.black.cgColor
            view.layer.shadowRadius = 4
            view.layer.shadowOffset = CGSize(width: 0, height: 4)
            view.clipsToBounds = false
        }
        let insetLayout = InsetLayout(insets: insets, sublayout: cardLayout)
        insetLayout.arrangement().makeViews(in: self.view)
```

And here is what I get:
<img width="263" alt="screen shot 2017-02-04 at 3 56 53 pm" src="https://cloud.githubusercontent.com/assets/3255391/22622581/e8d89d80-eaf2-11e6-9c02-3806d3a5c609.png">
<img width="394" alt="screen shot 2017-02-04 at 3 56 59 pm" src="https://cloud.githubusercontent.com/assets/3255391/22622582/e8d8a7ee-eaf2-11e6-9744-f0ec56ba34ff.png">

As you can see, everything is laid out properly, but the 'card' inset view is not properly drawing a shadow.

**Comment by nicksnyder** [comment]
You need to set a nonzero shadow opacity

```
view.layer.shadowOpacity = 1
```

**Comment by AttilaTheFun** [comment]
@nicksnyder why is that necessary - it normally defaults to 0, meaning that the gradient for the shadow goes from your shadow color to clear. If it's set to opaque it goes to white and all the pixels have an alpha value of 1 I believe.

**Comment by nicksnyder** [comment]
@AttilaTheFun A default opacity of 0 means "completely transparent" which means your shadow is not visible. Alpha value of 1 means "opaque", not "white".

https://developer.apple.com/reference/quartzcore/calayer/1410751-shadowopacity?language=objc
